server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: transaction.exchange
    queue: transaction.queue
    routingkey: transaction.routingkey
